# Use the latest image built as this is what is under test
FROM hbpmip/meta-db-setup:latest

COPY test-variables.json /src/variables/test.json
COPY new-test.patch.json /src/patches/new-test.patch.json

ENV TAXONOMIES=test|test_table|montrealcognitiveassessment,minimentalstate \
    TAXONOMY_PATCHES=test|new-test|test_table|montrealcognitiveassessment,minimentalstate
